[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "imaqbindings"
version = "0.1.0"
description = "Bindings for NI-IMAQ"
authors = [{ name = "T. D. Weber", email = "tweber@mit.edu" }]
license = {text = "MIT"}
dependencies = ["numpy>=1.21.0"]
